#include <iostream>
#include <string>
#include <cmath>
#include <cwctype>
#include <cctype>
#include <cstring>
#include "utils.hpp"


using namespace std;

void printIntro(string intro[], int arrsize){
    int i;
    char under = '-';
    for(i = 0; i < arrsize; i++){
        if (i != 0){
            int append = floor((60 - intro[i].length())/2);
            string concat = string(append,under) + intro[i] + string(append,under);
            cout << concat << endl;
        }
        else{
            cout << intro[i] << endl;
        }
    }
    cout << endl;
}

int main() {

    string stars(60,'*');

    string welcome_message[6] = {stars, 
        "Welcome to the Palindrome checker!",
        "Command to quit the program -> exit-",
        "Otherwise the program will loop until terminated",
        "Only alphanumeric strings are considered valid input",
        stars};

    printIntro(welcome_message, 6);
    string user_palin;
    bool ask_again = true;

    while (ask_again){

        string user_palin;
        //Receive input
        cout << "Is it a Palindrome!? Check here: ";
        cin >> user_palin;
        cout << endl;

        //Check that input is alphanumeric and not whitespace
        if(!isAlphanum(user_palin)){
            continue;
        }
        //Check for exit statement
        else if(user_palin == "exit"){
            break;
        }
        else{
            //Convert upper case to lower
            string sanitized = convertCase(user_palin);
            //Pass to checking function 
            cout << std::boolalpha << isPalindrome(sanitized) << endl;
        }
        
    }
    
    return 0;
}



/*
Assumptions of program:

-Only positive valued Alphanumeric strings or integers are considered valid input
-Symbols will not be considered Alphanumeric
-Test plan present within a seperate script
-Test cases will be ran from a test script runner
-Test Report will be generated by runner
-Palindrome will be ran from the terminal 
-User input in interactive terminal loops till terminated
-Input palindormes will be at most 100 charac
*/
